services:
  webui:
    image: ghcr.io/open-webui/open-webui
    container_name: webui
    restart: unless-stopped
    networks:
      - reverse-proxy_net
    environment:
      - VIRTUAL_HOST=webui.buldev.com
      - LETSENCRYPT_HOST=webui.buldev.com
    volumes:
      - ./data:/app/backend/data
    dns:
      - 8.8.8.8  # Google DNS
      - 8.8.4.4  # Google DNS secondary
      - 1.1.1.1  # Cloudflare DNS (optional)

networks:
  reverse-proxy_net:
    external: true
