services:
  webui:
    image: ghcr.io/open-webui/open-webui
    container_name: webui
    restart: unless-stopped
    networks:
      - net
    environment:
      - VIRTUAL_HOST=webui.gchalakov.com
      - LETSENCRYPT_HOST=webui.gchalakov.com
    volumes:
      - open-webui:/app/backend/data

networks:
  net:
    external: true

volumes:
  open-webui:
