services:
  webui:
    image: ghcr.io/open-webui/open-webui
    container_name: webui
    restart: unless-stopped
    networks:
      - reverse-proxy_net
    environment:
      - VIRTUAL_HOST=webui.buldev.com
      - LETSENCRYPT_HOST=webui.buldev.com
    volumes:
      - ./data:/app/backend/data

networks:
  reverse-proxy_net:
    external: true
